/// Python 沙盒配置。
///
/// 定义 [PythonPlugin] 中 `run_python` / `run_python_file` 工具的沙盒约束：
/// - 禁用模块列表（通过 Chaquopy import hook 拦截）
/// - 代码大小限制
/// - 超时限制
/// - stdout/stderr 截断阈值
///
/// sitecustomize.py 内容由 [sitecustomizeContent] 提供，
/// ChaquopyBridge 在初始化时写入 Python 临时目录。
class PythonSandboxConfig {
  /// 禁用的模块列表（防止 Python 反向逃逸出沙盒）。
  ///
  /// 这些模块允许 Python 进程执行系统命令、网络访问、进程创建等危险操作，
  /// 在沙盒环境中必须禁用。
  static const blockedModules = <String>[
    'subprocess',
    'os.system',
    'os.popen',
    'os.exec',
    'os.execv',
    'os.execve',
    'os.fork',
    'os.kill',
    'os.spawn',
    'socket',
    'ctypes',
    'multiprocessing',
    'asyncio.subprocess',
    'shutil',
    'signal',
  ];

  /// 代码最大字节数（100KB）。
  static const int maxCodeBytes = 100 * 1024;

  /// stdout/stderr 各最大字节数（50KB，与 ShellPlugin 一致）。
  static const int maxOutputBytes = 50 * 1024;

  /// 默认超时毫秒。
  static const int defaultTimeoutMs = 30000;

  /// 最大超时毫秒。
  static const int maxTimeoutMs = 120000;

  /// 最小超时毫秒。
  static const int minTimeoutMs = 1000;

  /// sitecustomize.py 内容：在 Python 启动时自动执行，安装 import hook 拦截禁用模块。
  ///
  /// 原理：覆盖 `builtins.__import__`，对 [blockedModules] 中的模块抛出 ImportError。
  static String get sitecustomizeContent => '''
# SpaceCode Mobile Python Sandbox - sitecustomize.py
# Auto-generated by PythonSandboxConfig. Do not edit.

import builtins
import sys

_BLOCKED_MODULES = frozenset({
${blockedModules.map((m) => "    '$m',").join('\n')}
})

_original_import = builtins.__import__

def _sandboxed_import(name, globals=None, locals=None, fromlist=(), level=0):
    # Check the full module path and its top-level package
    parts = name.split('.')
    for i in range(len(parts), 0, -1):
        prefix = '.'.join(parts[:i])
        if prefix in _BLOCKED_MODULES:
            raise ImportError(
                f"Module '{prefix}' is blocked by SpaceCode sandbox. "
                f"Access to system/subprocess/network modules is restricted."
            )
    return _original_import(name, globals, locals, fromlist, level)

builtins.__import__ = _sandboxed_import

# Also remove any pre-imported blocked modules
for mod_name in list(sys.modules.keys()):
    if mod_name in _BLOCKED_MODULES:
        del sys.modules[mod_name]

print("[SpaceCode Sandbox] Import restrictions active.", file=sys.stderr)
''';
}
